version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    container_name: students
    image: katerinapoposka/appstudents:latest
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - students

  # Spring Boot Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - students

networks:
  students:
    driver: bridge
